// Tabela de cultivares do SISDEVIN, emitida em 30/03/2023: código, nome, cor e tipo, como na fonte
// (decidido em 03/10/2026). Fora só a linha "teste excluir" (código 49211), que é sujeira da tabela.
// Fonte: https://www.agricultura.rs.gov.br/upload/arquivos/202303/30112422-sisdevin-lista-cultivares-atualizado-em-marco-de-2023.pdf

export const FONTE_CULTIVARES = 'SISDEVIN, lista de cultivares de 30/03/2023'

export const CULTIVARES: ReadonlyArray<
  readonly [
    codigo: string,
    nome: string,
    cor: 'tinta' | 'branca' | 'rosada',
    tipo: 'vinifera' | 'americana_hibrida',
  ]
> = [
  ['1481', 'Alfrocheiro', 'tinta', 'vinifera'],
  ['1007', 'Alicante Bouschet', 'tinta', 'vinifera'],
  ['2003', 'Aligoté', 'branca', 'vinifera'],
  ['3000', 'Alphonse Lavallée', 'tinta', 'vinifera'],
  ['2011', 'Altesse', 'branca', 'vinifera'],
  ['2504', 'Alvarinho', 'branca', 'vinifera'],
  ['7072', 'Alwood', 'tinta', 'americana_hibrida'],
  ['1384', 'Ancellotta', 'tinta', 'vinifera'],
  ['49391', 'Ansonica', 'branca', 'vinifera'],
  ['1015', 'Aramon', 'tinta', 'vinifera'],
  ['1550', 'Arinarnoa', 'tinta', 'vinifera'],
  ['2380', 'Arriloba', 'branca', 'vinifera'],
  ['1660', 'Aspirant Bouschet', 'tinta', 'vinifera'],
  ['3191', 'Autumn Seedless', 'branca', 'vinifera'],
  ['2020', 'Auxerrois', 'branca', 'vinifera'],
  ['4006', 'Bacarina', 'tinta', 'americana_hibrida'],
  ['8001', 'Baco Blanc', 'branca', 'americana_hibrida'],
  ['7080', 'Bailey', 'tinta', 'americana_hibrida'],
  ['1023', 'Barbera (Piemont)', 'tinta', 'vinifera'],
  ['3342', 'Benitaka', 'rosada', 'vinifera'],
  ['3259', 'Black Magic', 'tinta', 'vinifera'],
  ['8141', 'Bokay', 'branca', 'americana_hibrida'],
  ['1031', 'Bonarda (Barbera Bonarda)', 'tinta', 'vinifera'],
  ['4014', 'Bordô (Ives)', 'tinta', 'americana_hibrida'],
  ['7005', 'Bourdin', 'tinta', 'americana_hibrida'],
  ['49470', 'Brachetto', 'tinta', 'vinifera'],
  ['8166', 'BRS Bibiana', 'branca', 'americana_hibrida'],
  ['7123', 'BRS Carmem', 'tinta', 'americana_hibrida'],
  ['3126', 'Brs Clara', 'branca', 'americana_hibrida'],
  ['7115', 'BRS Cora', 'tinta', 'americana_hibrida'],
  ['3232', 'BRS Isis', 'rosada', 'americana_hibrida'],
  ['3134', 'Brs Linda', 'branca', 'americana_hibrida'],
  ['8125', 'BRS Lorena', 'branca', 'americana_hibrida'],
  ['7140', 'BRS Magna', 'tinta', 'americana_hibrida'],
  ['7131', 'BRS Margot', 'tinta', 'americana_hibrida'],
  ['3142', 'Brs Morena', 'tinta', 'americana_hibrida'],
  ['3240', 'BRS Núbia', 'tinta', 'americana_hibrida'],
  ['7099', 'BRS Rúbea', 'tinta', 'americana_hibrida'],
  ['7107', 'BRS Violeta', 'tinta', 'americana_hibrida'],
  ['3224', 'BRS Vitória', 'tinta', 'americana_hibrida'],
  ['2038', 'Burger', 'branca', 'vinifera'],
  ['49474', 'Busuioaca de Bohotin', 'rosada', 'vinifera'],
  ['1040', 'Cabernet Franc', 'tinta', 'vinifera'],
  ['1058', 'Cabernet Sauvignon', 'tinta', 'vinifera'],
  ['1585', 'Caladoc', 'tinta', 'vinifera'],
  ['1066', 'Calitor (Sira Falsa)', 'tinta', 'vinifera'],
  ['1074', 'Campanario', 'tinta', 'vinifera'],
  ['1082', 'Canaiolo', 'tinta', 'vinifera'],
  ['3101', 'Cardinal', 'rosada', 'vinifera'],
  ['1090', 'Carignane', 'tinta', 'vinifera'],
  ['1104', 'Carmenere', 'tinta', 'vinifera'],
  ['1457', 'Castelão (Piriquita)', 'tinta', 'vinifera'],
  ['49480', 'Catarratto Bianco', 'branca', 'vinifera'],
  ['2054', 'Cereza', 'rosada', 'vinifera'],
  ['2046', 'CG 531', 'rosada', 'vinifera'],
  ['4081', 'Champagnon (Champanheta)', 'tinta', 'americana_hibrida'],
  ['2062', 'Chardonnay', 'branca', 'vinifera'],
  ['2070', 'Chasselas', 'branca', 'vinifera'],
  ['2089', 'Chenin Blanc', 'branca', 'vinifera'],
  ['1112', 'Cinsaut', 'tinta', 'vinifera'],
  ['2097', 'Clairette de Provence', 'branca', 'vinifera'],
  ['1120', 'Clairette Noir', 'tinta', 'vinifera'],
  ['4022', 'Clinton', 'tinta', 'americana_hibrida'],
  ['49484', 'Cococciola', 'branca', 'vinifera'],
  ['9070', 'Coleções', 'tinta', 'americana_hibrida'],
  ['2100', 'Colombard', 'branca', 'vinifera'],
  ['4124', 'Concord Clone 30', 'tinta', 'americana_hibrida'],
  ['4030', 'Concord (Francesa)', 'tinta', 'americana_hibrida'],
  ['3018', 'Corniola de Milazzo', 'branca', 'vinifera'],
  ['2402', 'Cortese', 'branca', 'vinifera'],
  ['1654', 'Corvina', 'tinta', 'vinifera'],
  ['7013', 'Couderc Tinta (Seibel 1077)', 'tinta', 'americana_hibrida'],
  ['8010', 'Couderc 13 (Branca)', 'branca', 'americana_hibrida'],
  ['3208', 'Crimson Seedless', 'rosada', 'vinifera'],
  ['1538', 'Croatina', 'tinta', 'vinifera'],
  ['4049', 'Cynthiana (Zeperina-Santiago)', 'tinta', 'americana_hibrida'],
  ['3077', 'Dedo de Dama', 'branca', 'vinifera'],
  ['8028', 'Delaware (Delarvare)', 'rosada', 'americana_hibrida'],
  ['1392', 'Dolcetto', 'tinta', 'vinifera'],
  ['8109', 'Dona Zilá', 'rosada', 'americana_hibrida'],
  ['1490', 'Dornfelder', 'tinta', 'vinifera'],
  ['1139', 'Durif', 'tinta', 'vinifera'],
  ['8036', 'Dutchess', 'branca', 'americana_hibrida'],
  ['1333', 'Egiodola', 'tinta', 'vinifera'],
  ['1620', 'Ekigaina', 'tinta', 'vinifera'],
  ['49495', 'Falanghina', 'branca', 'vinifera'],
  ['49549', 'Favorita', 'branca', 'vinifera'],
  ['3167', 'Festival (Sugraone)', 'tinta', 'vinifera'],
  ['3216', 'Flame Seedless', 'rosada', 'vinifera'],
  ['49499', 'Fleurtai', 'branca', 'vinifera'],
  ['2119', 'Flora', 'rosada', 'vinifera'],
  ['1341', 'Franconia', 'tinta', 'vinifera'],
  ['1147', 'Freisa', 'tinta', 'vinifera'],
  ['1163', 'Gamay Noir (Beaujolais)', 'tinta', 'vinifera'],
  ['1155', 'Gamay Saint Romain', 'tinta', 'vinifera'],
  ['2410', 'Garganega', 'branca', 'vinifera'],
  ['2127', 'Gewurztraminer', 'branca', 'vinifera'],
  ['8044', 'Goethe (Gota de Ouro / Pinot)', 'rosada', 'americana_hibrida'],
  ['9008', 'Golden Queen', 'branca', 'americana_hibrida'],
  ['2512', 'Gouveio', 'branca', 'vinifera'],
  ['1171', 'Grand Noir de la Calmette', 'tinta', 'vinifera'],
  ['49500', 'Grechetto', 'branca', 'vinifera'],
  ['1180', 'Grenache', 'tinta', 'vinifera'],
  ['2399', 'Gros Manseng', 'branca', 'vinifera'],
  ['4057', 'Herbemont (Borgonha/Champanhe)', 'tinta', 'americana_hibrida'],
  ['8052', 'IAC', 'branca', 'americana_hibrida'],
  ['49502', 'Irsai Oliver', 'branca', 'vinifera'],
  ['4065', 'Isabel (Brasileira)', 'tinta', 'americana_hibrida'],
  ['4116', 'Isabel Precoce', 'tinta', 'americana_hibrida'],
  ['3026', 'Itália (Pirovano 65)', 'branca', 'vinifera'],
  ['4073', 'Jacquez (Seibel/Pica Longa)', 'tinta', 'americana_hibrida'],
  ['1524', 'Jaen', 'tinta', 'vinifera'],
  ['5028', 'Juliana', 'branca', 'americana_hibrida'],
  ['3085', 'Kyoho', 'tinta', 'americana_hibrida'],
  ['49503', 'Labrusco di Sorbara', 'tinta', 'vinifera'],
  ['1601', 'Lagrein', 'tinta', 'vinifera'],
  ['1198', 'Lambrusco', 'tinta', 'vinifera'],
  ['7021', 'Landot', 'tinta', 'americana_hibrida'],
  ['49504', 'Macabeo', 'branca', 'vinifera'],
  ['2135', 'Maccabeo', 'branca', 'vinifera'],
  ['1201', 'Malbec', 'tinta', 'vinifera'],
  ['2143', 'Malvasia Amarela', 'branca', 'vinifera'],
  ['2151', 'Malvasia Bianca', 'branca', 'vinifera'],
  ['2445', 'Malvasia Chianti', 'branca', 'vinifera'],
  ['2160', 'Malvasia de Cândia', 'branca', 'vinifera'],
  ['49508', 'Malvasia di Sardegna', 'branca', 'vinifera'],
  ['2470', 'Malvasia Istriana', 'branca', 'vinifera'],
  ['2178', 'Malvasia Verde', 'branca', 'vinifera'],
  ['1541', 'Marselan', 'tinta', 'vinifera'],
  ['8060', 'Martha', 'rosada', 'americana_hibrida'],
  ['1210', 'Marzemina', 'tinta', 'vinifera'],
  ['1228', 'Merlot', 'tinta', 'vinifera'],
  ['4', 'Mistura de uvas americanas branco', 'branca', 'americana_hibrida'],
  ['6', 'Mistura de uvas americanas rosado', 'rosada', 'americana_hibrida'],
  ['7', 'Mistura de uvas americanas tinto', 'tinta', 'americana_hibrida'],
  ['1', 'Mistura de uvas viníferas branco', 'branca', 'vinifera'],
  ['2', 'Mistura de uvas viníferas rosado', 'rosada', 'vinifera'],
  ['3', 'Mistura de uvas viníferas tinto', 'tinta', 'vinifera'],
  ['1646', 'Molinara', 'tinta', 'vinifera'],
  ['1422', 'Montepulciano', 'tinta', 'vinifera'],
  ['1593', 'Moreto', 'tinta', 'vinifera'],
  ['2186', 'Moscatel Nazareno', 'branca', 'vinifera'],
  ['4090', 'Moscato Bailey', 'tinta', 'vinifera'],
  ['2461', 'Moscato Bianco R2', 'branca', 'vinifera'],
  ['2194', 'Moscato Branco', 'branca', 'vinifera'],
  ['3118', 'Moscato de Alexandria', 'branca', 'vinifera'],
  ['2429', 'Moscato de Canalli', 'branca', 'vinifera'],
  ['3042', 'Moscato de Hamburgo', 'tinta', 'vinifera'],
  ['8117', 'Moscato Embrapa', 'branca', 'americana_hibrida'],
  ['2437', 'Moscato Giallo', 'branca', 'vinifera'],
  ['3050', 'Moscato Rosado', 'rosada', 'vinifera'],
  ['1679', 'Mouvedre', 'tinta', 'vinifera'],
  ['2208', 'Muller Thurgau', 'branca', 'vinifera'],
  ['2216', 'Muscadelle', 'branca', 'vinifera'],
  ['1703', 'Muscat à Petits Grains', 'branca', 'vinifera'],
  ['1236', 'Napa Gamay (Valdiguié)', 'tinta', 'vinifera'],
  ['49509', 'Nasco', 'branca', 'vinifera'],
  ['1244', 'Nebbiolo', 'tinta', 'vinifera'],
  ['3268', 'Niabel', 'tinta', 'americana_hibrida'],
  ['5002', 'Niágara Branca', 'branca', 'americana_hibrida'],
  ['5010', 'Niágara Rosada', 'rosada', 'americana_hibrida'],
  ['7030', 'Oberlin', 'tinta', 'americana_hibrida'],
  ['3326', 'Ora', 'branca', 'vinifera'],
  ['49510', 'Ortrugo', 'branca', 'vinifera'],
  ['7048', 'Othello (Sta. Justina/Mendoza)', 'tinta', 'americana_hibrida'],
  ['4132', 'Paco', 'tinta', 'americana_hibrida'],
  ['49511', 'Palava', 'rosada', 'vinifera'],
  ['2224', 'Palomino', 'branca', 'vinifera'],
  ['49512', 'Parellada', 'branca', 'vinifera'],
  ['49513', 'Passerina', 'branca', 'vinifera'],
  ['3093', 'Patrícia', 'tinta', 'americana_hibrida'],
  ['49514', 'Pecorino', 'branca', 'vinifera'],
  ['3069', 'Perlona (Pirovano 54)', 'branca', 'vinifera'],
  ['2567', 'Petit Manseng', 'branca', 'vinifera'],
  ['1516', 'Petit Verdot', 'tinta', 'vinifera'],
  ['1252', 'Petite Syrah', 'tinta', 'vinifera'],
  ['2232', 'Peverella', 'branca', 'vinifera'],
  ['49515', 'Pignoletto', 'branca', 'vinifera'],
  ['2240', 'Pinot Blanc', 'branca', 'vinifera'],
  ['2259', 'Pinot Gris', 'rosada', 'vinifera'],
  ['1279', 'Pinot Noir', 'tinta', 'vinifera'],
  ['1287', 'Pinot Saint George', 'tinta', 'vinifera'],
  ['1260', 'Pinotage', 'tinta', 'vinifera'],
  ['8158', 'Poloske', 'branca', 'americana_hibrida'],
  ['3334', 'Prima', 'tinta', 'vinifera'],
  ['0', 'Primitivo', 'tinta', 'vinifera'],
  ['2267', 'Prosecco', 'branca', 'vinifera'],
  ['1569', 'Rebo', 'tinta', 'vinifera'],
  ['3175', 'Red Globe', 'rosada', 'vinifera'],
  ['1430', 'Refosco', 'tinta', 'vinifera'],
  ['3159', 'Ribol', 'tinta', 'vinifera'],
  ['49540', 'Ribuele', 'branca', 'vinifera'],
  ['2275', 'Riesling Itálico', 'branca', 'vinifera'],
  ['2283', 'Riesling Renano', 'branca', 'vinifera'],
  ['1638', 'Rondinella', 'tinta', 'vinifera'],
  ['1687', 'Roobernet', 'tinta', 'vinifera'],
  ['3034', 'Rubi (Itália Rubi/Itália Rosa)', 'rosada', 'vinifera'],
  ['1295', 'Ruby Cabernet', 'tinta', 'vinifera'],
  ['1738', 'Sagratino', 'tinta', 'vinifera'],
  ['1309', 'Sangiovese', 'tinta', 'vinifera'],
  ['1746', 'Saperavi', 'tinta', 'vinifera'],
  ['2291', 'Sauvignon Blanc', 'branca', 'vinifera'],
  ['2538', 'Sauvignon gris', 'rosada', 'vinifera'],
  ['2488', 'Schönburger', 'rosada', 'vinifera'],
  ['2305', 'Seara Nova', 'branca', 'vinifera'],
  ['4108', 'Seibel', 'tinta', 'americana_hibrida'],
  ['4102', 'Seibel-2 (Seibeleto)', 'tinta', 'americana_hibrida'],
  ['9062', 'Seleções', 'branca', 'americana_hibrida'],
  ['2313', 'Semillon', 'branca', 'vinifera'],
  ['7064', 'Seyve Villard - Tinta', 'tinta', 'americana_hibrida'],
  ['8087', 'Seyve Villard 12375 (Villard Blanc)', 'branca', 'americana_hibrida'],
  ['8079', 'Seyve Villard 5276', 'branca', 'americana_hibrida'],
  ['49543', 'Soreli', 'branca', 'vinifera'],
  ['2321', 'Sylvaner', 'branca', 'vinifera'],
  ['1317', 'Tannat', 'tinta', 'vinifera'],
  ['8095', 'Tardia de Caxias', 'rosada', 'americana_hibrida'],
  ['1350', 'Tempranillo', 'tinta', 'vinifera'],
  ['1406', 'Teroldego', 'tinta', 'vinifera'],
  ['3183', 'Thompson Seedless (Sultanina)', 'branca', 'vinifera'],
  ['1376', 'Tinta Barroca', 'tinta', 'vinifera'],
  ['1577', 'Tinta caiada', 'tinta', 'vinifera'],
  ['1449', 'Tinta Roriz', 'tinta', 'vinifera'],
  ['2330', 'Tocai Friulano', 'branca', 'vinifera'],
  ['1368', 'Torrontes', 'tinta', 'vinifera'],
  ['1473', 'Touriga Francesa', 'tinta', 'vinifera'],
  ['1414', 'Touriga Nacional', 'tinta', 'vinifera'],
  ['2348', 'Trebbiano (S.Émillion/Ugni B.)', 'branca', 'vinifera'],
  ['2559', 'Trebbiano Toscano', 'branca', 'vinifera'],
  ['1465', 'Trincadeira', 'tinta', 'vinifera'],
  ['1695', 'Uva Longanesi', 'tinta', 'vinifera'],
  ['7056', 'Vênus', 'tinta', 'americana_hibrida'],
  ['2372', 'Verdea (Perdea)', 'branca', 'vinifera'],
  ['2540', 'Verdelho', 'branca', 'vinifera'],
  ['2453', 'Verdiso', 'branca', 'vinifera'],
  ['2356', 'Vermentino', 'branca', 'vinifera'],
  ['2364', 'Vernaccia', 'branca', 'vinifera'],
  ['8133', 'Villenave', 'branca', 'americana_hibrida'],
  ['2526', 'Viogner', 'branca', 'vinifera'],
  ['2496', 'Viognier', 'branca', 'vinifera'],
  ['49550', 'Xarello', 'branca', 'vinifera'],
  ['1325', 'Zinfandel', 'tinta', 'vinifera'],
]
